name: check-not-broken

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-not-broken:
    runs-on: ubuntu-latest
    steps:
      - name: make environment
        uses: ./.github/actions/make-environment
      - run: make check-not-broken
