name: check-not-broken

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main

jobs:
  check-not-broken:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: make environment
        uses: ./.github/actions/make-environment
      - run: make check-not-broken
