name: release-to-github

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
