name: release-to-crates-io

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  release-to-crates-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${CRATES_API_TOKEN}
        env:
          CRATES_API_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
