name: release-to-github

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "Tag to release"
        required: true
  workflow_call:
    inputs:
      tag:
        type: string
        description: "Tag to release"
        required: true

jobs:
  release-to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          allowUpdates: true
