name: release-to-github

on:
  workflow_dispatch:
    inputs:
      tag-to-release:
        type: string
        description: "Tag to release"
        required: true
      changelog:
        type: string
        description: "Changelog"
        required: false
  workflow_call:
    inputs:
      tag-to-release:
        type: string
        description: "Tag to release"
        required: true
      changelog:
        type: string
        description: "Changelog"
        required: false

jobs:
  release-to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag-to-release }}
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag-to-release }}
          skipIfReleaseExists: true
          body: ${{ inputs.changelog }}
